import type {
  Profile, Prospect, Client, Devis, DevisLigne,
  Projet, Interaction, MrrDataPoint, Setting,
} from './types';

// --- Profiles ---
export const mockProfiles: Profile[] = [
  {
    id: 'u1', email: 'kevin@solayia.fr', full_name: 'Kevin',
    role: 'admin', avatar_url: null, created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'u2', email: 'adrien@solayia.fr', full_name: 'Adrien Lechevalier',
    role: 'membre', avatar_url: null, created_at: '2024-03-01T09:00:00Z',
  },
];

// --- Prospects (donnees CRM Solayia - Produit cible: Solayia uniquement) ---
export const mockProspects: Prospect[] = [
  {
    id: 'p1',
    nom: 'KERBRAT',
    prenom: 'Anthony',
    entreprise: 'ENTREPRISE KERBRAT',
    email: 'anthony.kerbrat31@gmail.com',
    telephone: '06 51 49 95 59',
    statut: 'r1',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Chauffage / Ventilation / Climatisation',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Physique, Téléphone',
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p2',
    nom: 'PRIMAUX',
    prenom: 'Cédric',
    entreprise: 'Family webdiffusion',
    email: 'cedricprimaux@famillywebdiffusion.com',
    telephone: '0582951450',
    statut: 'prise_contact',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'Autre',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: null,
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Sextoys',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'Email',
    derniere_communication: '20 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.loveandvibes.fr/',
    traits_personnalite: null,
  },
  {
    id: 'p3',
    nom: 'BOYER',
    prenom: 'Frédérique',
    entreprise: 'Kesame',
    email: 'frederic.boyer@kesame.fr',
    telephone: '0651283243',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prescripteur',
    source: 'BNI, Réseau',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Courtier professionnel',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Physique',
    dernier_canal: 'Visio',
    derniere_communication: '31 mars 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p4',
    nom: 'TAIANA',
    prenom: 'Bruno',
    entreprise: '',
    email: 'brunotaiana@hotmail.fr',
    telephone: '0685621685',
    statut: 'r1',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'Réseau',
    produit_cible: 'Solayia',
    notes: 'PROJET :\ngrâce à l\'IA, analyse geste et posture du personnel dans les collectivités.\nquelles sont les charges, les contraintes physiques dans la journée\net analyser\net proposer exercice\npar poste\n\naujourd\'hui fiche metier\n\norganisme qui gagne plein de sous\nformation adaptée\nloin de la réalité\n\nêtre plus précis et personnalisé selon la personne\noutil qui te permettrait de proposer des exercices',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Email, Physique, Téléphone, Visio',
    dernier_canal: 'Email',
    derniere_communication: '27 mars 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p5',
    nom: 'AUJOULAT',
    prenom: 'Maïté',
    entreprise: 'Immo AM',
    email: 'maite.aujoulat@immo-am.com',
    telephone: '06 64 21 52 35',
    statut: 'prospect',
    temperature: 'tiede',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: 'No go à cause des 49€/mois \nA relancer plus tard\nDiscussion avec un infogérant',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'normale',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Agent immo part',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Physique, SMS, Visio, Whatsapp',
    dernier_canal: 'Whatsapp',
    derniere_communication: '17 avril 2026',
    drive_dedie: 'https://drive.google.com/drive/folders/1B1Wf1Eplx4-XkbxGyl5cDk_VKk8e0vA9?hl=fr',
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: 'https://www.pappers.fr/entreprise/immo-am-immobilier-aujoulat-maite-942570698',
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: 'Couleur préféré : vert\nDouce, exigeante, lente',
  },
  {
    id: 'p6',
    nom: 'SALLES',
    prenom: 'Fabien',
    entreprise: 'Installe ta clim',
    email: '',
    telephone: '06 73 31 74 55',
    statut: 'suivi',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Climatisation',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Physique, SMS, Visio',
    dernier_canal: 'Visio',
    derniere_communication: '31 mars 2026',
    drive_dedie: null,
    fichiers_medias: 'https://docs.google.com/presentation/d/1Z9b0lHUG-qDhgfyCOm4t9Nw05IDCrZuXw_yWdP9IL8c/edit?slide=id.g3c9d5bdf54a_0_0#slide=id.g3c9d5bdf54a_0_0',
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p7',
    nom: 'CAYLA',
    prenom: 'Laurent',
    entreprise: 'EDLCDIAG',
    email: '',
    telephone: '06 01 33 61 60',
    statut: 'r1',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Diagnostic',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Physique, SMS',
    dernier_canal: 'Physique',
    derniere_communication: '3 avril 2026',
    drive_dedie: null,
    fichiers_medias: 'https://drive.google.com/drive/folders/1PrXhU-wAQ3h49tmSBK8SWK9X47DFHS5T?hl=fr',
    fonction: 'Solopreneur',
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p8',
    nom: 'PEDO',
    prenom: 'Béatrice',
    entreprise: 'Oxymore Consulting',
    email: '',
    telephone: '06 75 52 35 43',
    statut: 'prise_contact',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: 'LP 1490e',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'DRH externalisé',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: 'Douce, carré, à l’écoute, besoin de dev son business',
  },
  {
    id: 'p9',
    nom: 'MAURY',
    prenom: 'Benoit',
    entreprise: 'TUC Vacances & Formation',
    email: 'directeur@toulouseuniversiteclub.fr',
    telephone: '06 30 03 04 16',
    statut: 'suivi',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'Réseau',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Stages & colo',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: 'Email, Physique, SMS, Visio',
    dernier_canal: 'Physique',
    derniere_communication: '29 mars 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p10',
    nom: 'Le ravelin (bar st cyp)',
    prenom: '',
    entreprise: 'Le ravelin (bar st cyp)',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p11',
    nom: 'Le père boulange (boulangerie st cyp)',
    prenom: '',
    entreprise: 'Le père boulange (boulangerie st cyp)',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p12',
    nom: 'Boucherie Les Fontaines',
    prenom: '',
    entreprise: 'Boucherie Les Fontaines',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p13',
    nom: 'Manolita',
    prenom: '',
    entreprise: 'Manolita',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p14',
    nom: 'La Gougnotte',
    prenom: '',
    entreprise: 'La Gougnotte',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p15',
    nom: 'Restaurant Ytaing Toulouse',
    prenom: '',
    entreprise: 'Restaurant Ytaing Toulouse',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://ytaing-fast-food.eatbu.com/?lang=fr#contact',
    traits_personnalite: null,
  },
  {
    id: 'p16',
    nom: 'Le panivore',
    prenom: '',
    entreprise: 'Le panivore',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.instagram.com/lepanivore/',
    traits_personnalite: null,
  },
  {
    id: 'p17',
    nom: 'BASTA',
    prenom: '',
    entreprise: '',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p18',
    nom: 'Antho & Rita',
    prenom: '',
    entreprise: 'Antho & Rita',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p19',
    nom: 'Le Trio Gourmand St Cyprien',
    prenom: '',
    entreprise: 'Le Trio Gourmand St Cyprien',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p20',
    nom: 'Les Chimères',
    prenom: '',
    entreprise: 'Les Chimères',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p21',
    nom: 'Le Fournil De La Place toulouse',
    prenom: '',
    entreprise: 'Le Fournil De La Place toulouse',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p22',
    nom: 'Tinto - café d\'altitude toulouse',
    prenom: '',
    entreprise: 'Tinto - café d\'altitude toulouse',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p23',
    nom: 'Mayumi',
    prenom: '',
    entreprise: 'Mayumi',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://mayumi-toulouse.tiiny.site/jpg/MAYUMI-MENU-VITRINE_page-0002',
    traits_personnalite: null,
  },
  {
    id: 'p24',
    nom: 'Bistrot 12',
    prenom: '',
    entreprise: 'Bistrot 12',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p25',
    nom: 'L’estaminot',
    prenom: '',
    entreprise: 'L’estaminot',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p26',
    nom: 'L’italien Toulouse',
    prenom: '',
    entreprise: 'L’italien Toulouse',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p27',
    nom: 'Hayuco',
    prenom: '',
    entreprise: 'Hayuco',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p28',
    nom: 'L’atelier du pêcheur',
    prenom: '',
    entreprise: 'L’atelier du pêcheur',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: 'Réel probleme page google envoie vers : https://ron.mamma.com/sports/?s1paid=873220&segment=rsoc.ron.mamma.001&s1pcid=atelier-du-pecheur.fr',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p29',
    nom: 'DOHA',
    prenom: 'Marie-Cecile',
    entreprise: 'Territoria Mutuelle',
    email: 'mc.doha@territoria-mutuelle.org',
    telephone: '0618417985',
    statut: 'prise_contact',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Mutuelle',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p30',
    nom: 'SANGARE',
    prenom: 'Moussa',
    entreprise: 'Yuma Brunch',
    email: '',
    telephone: '0766867176',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p31',
    nom: 'DAMBRE',
    prenom: 'Elodie',
    entreprise: 'Cap sur l\'Audace',
    email: '',
    telephone: '0625325583',
    statut: 'prise_contact',
    temperature: 'tiede',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'normale',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Cap sur l\'Audace',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p32',
    nom: 'GUILLOT',
    prenom: 'Virginie',
    entreprise: '',
    email: '',
    telephone: '0659428348',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: null,
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p33',
    nom: 'ROLLIN',
    prenom: 'Nicolas',
    entreprise: 'Abeille Verte',
    email: 'nicolas.rollin@abeille-verte.fr',
    telephone: '0637005796',
    statut: 'prospect',
    temperature: 'chaud',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: 'Lance nouvelle activité en septembre (ramonage). \nA relancer juin 2026',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'haute',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: '1/ nettoyage toiture 2/ ramonage',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'SMS',
    derniere_communication: '12 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: 'Sympathique, sud ouest, gaillard (fête de condom)',
  },
  {
    id: 'p34',
    nom: 'SENDRA',
    prenom: 'Fabrice',
    entreprise: 'Styl’o Bat',
    email: 'stylobat31@gmail.com',
    telephone: '0622255051',
    statut: 'prise_contact',
    temperature: 'tiede',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'normale',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Peintre en bâtiment',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'SMS',
    derniere_communication: '12 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.stylobat-peinture.fr/',
    traits_personnalite: null,
  },
  {
    id: 'p35',
    nom: 'CHASTRES-SARIEGO',
    prenom: 'Stéphanie',
    entreprise: 'Alarian Solutions',
    email: '',
    telephone: '+33782781576',
    statut: 'perdu',
    temperature: 'tiede',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'normale',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Back-office freelance',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: 'https://solayia.github.io/alarian-solutions/',
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.alarian-solutions.fr/',
    traits_personnalite: null,
  },
  {
    id: 'p36',
    nom: 'CLIMENT',
    prenom: 'Anais',
    entreprise: 'Reno Services 31',
    email: '',
    telephone: '0640168508',
    statut: 'prise_contact',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'BNI',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Décoratrice d’intérieur',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'Whatsapp',
    derniere_communication: '20 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: 'https://solayia.github.io/reno-services-31/',
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p37',
    nom: 'Les Canalisateurs',
    prenom: '',
    entreprise: 'Les Canalisateurs',
    email: 'info@canalisateurs.com',
    telephone: '',
    statut: 'prise_contact',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'Spontanée',
    produit_cible: 'Solayia',
    notes: 'Email général : info@canalisateurs.com \nNathalie Gaudion — Chargée de mission Environnement, Qualité, Label Canalisateur : nathalie.gaudion@canalisateurs.com \nGatien Félix — Conseiller technique et prévention : gatien.felix@canalisateurs.com \nValentina Gaviria Santos — Chargée de mission Économie, Emploi, Formation : valentina.gaviriasantos@canalisateurs.com',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Canalisation',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'Email',
    derniere_communication: '20 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.canalisateurs.com/',
    traits_personnalite: null,
  },
  {
    id: 'p38',
    nom: 'Bati France Construction',
    prenom: '',
    entreprise: 'Bati France Construction',
    email: 'contact@batifranceconstruction.com',
    telephone: '06 34 35 36 29 // 06 27 43 18 46',
    statut: 'prise_contact',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'Spontanée',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Entreprise générale du batîment',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'Email',
    derniere_communication: '20 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: 'https://solayia.github.io/bati-france-construction/',
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://batifranceconstruction.com/',
    traits_personnalite: null,
  },
  {
    id: 'p39',
    nom: 'GIACOSA',
    prenom: 'Ludyvine',
    entreprise: 'Codeco',
    email: '',
    telephone: '0648292752',
    statut: 'prise_contact',
    temperature: 'froid',
    type_contact: 'prospect',
    source: 'Spontanée',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Maitrise d’oeuvre',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'SMS',
    derniere_communication: '20 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: 'https://solayia.github.io/codeco/',
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p40',
    nom: 'Somafi Group',
    prenom: '',
    entreprise: 'Somafi Group',
    email: 'sav@somafi.net',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: null,
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Fermetures industrielles / équipement quais',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://somafi-group.fr/',
    traits_personnalite: null,
  },
  {
    id: 'p41',
    nom: 'Les compagnons Midi-Pyrénées',
    prenom: '',
    entreprise: 'Les compagnons Midi-Pyrénées',
    email: 'couvreur3119@gmail.com',
    telephone: '07 88 24 98 12',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: null,
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Couvreur',
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: 'https://www.les-compagnons-midipyrenees.fr/',
    traits_personnalite: null,
  },
  {
    id: 'p42',
    nom: 'BARANES',
    prenom: 'Daniel',
    entreprise: '',
    email: 'daniel.baranes@dbmail.com',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: 'Bonjour,\nQue ce soit pour attirer de nouveaux clients ou pour augmenter votre taux de transformation sur vos devis, un excellent site web et une bonne e-réputation sont aujourd’hui devenus primordiaux.\nAvec mon équipe, nous aimons créer des maquettes gratuites de sites internet pour montrer aux dirigeants qu’ils peuvent attirer plus facilement de nouveaux clients grâce à un bon design, un contenu clair et un bon référencement.\nSans plus attendre, voici votre maquette gratuite : \nSeriez-vous d...',
    assigned_to: null,
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Plomberie',
    adresse: '41 Rue de Caumont, 31500 Toulouse',
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p43',
    nom: 'MOYNET',
    prenom: 'Nicolas',
    entreprise: 'Solutions Terrain',
    email: '',
    telephone: '0687389302',
    statut: 'r1',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: null,
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: 'Collecte de données d\'études marketing',
    adresse: '116 route d’Espagne, Toulouse',
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: null,
    derniere_communication: null,
    drive_dedie: null,
    fichiers_medias: null,
    fonction: 'Directeur général',
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
  {
    id: 'p44',
    nom: 'Helene Madranges',
    prenom: '',
    entreprise: 'Helene Madranges',
    email: '',
    telephone: '',
    statut: 'prospect',
    temperature: 'froid',
    type_contact: 'prospect',
    source: '',
    produit_cible: 'Solayia',
    notes: 'Linkedin : https://www.linkedin.com/in/helene-madranges-553897224/\nElle a liké mon post sur LinkedIn et ajouté.\nElle a une homonymes. \nElle semble ne pas avoir de site internet.',
    assigned_to: 'u2',
    type_prestation: null,
    description_prestation: null,
    adresse_chantier: null,
    tarif_propose: null,
    date_premier_contact: null,
    date_relance: null,
    urgence: 'basse',
    created_at: '2026-04-24T15:19:00Z',
    updated_at: '2026-04-24T15:19:00Z',
    activite: null,
    adresse: null,
    ca_en_k: null,
    canaux_privilegies: null,
    dernier_canal: 'Linkedin',
    derniere_communication: '27 mai 2026',
    drive_dedie: null,
    fichiers_medias: null,
    fonction: null,
    maquette_solayia: null,
    pappers: null,
    prescripteur_ref: null,
    site_web: null,
    traits_personnalite: null,
  },
];

// --- Clients ---
export const mockClients: Client[] = [];

// --- Devis ---
export const mockDevisLignes: DevisLigne[] = [];
export const mockDevis: Devis[] = [];

// --- Projets ---
export const mockProjets: Projet[] = [];

// --- Interactions ---
export const mockInteractions: Interaction[] = [];

// --- MRR History (12 mois) ---
export const mockMrrHistory: MrrDataPoint[] = [
  { mois: 'Juin 25', mrr: 0 },
  { mois: 'Juil 25', mrr: 0 },
  { mois: 'Aout 25', mrr: 0 },
  { mois: 'Sep 25', mrr: 0 },
  { mois: 'Oct 25', mrr: 0 },
  { mois: 'Nov 25', mrr: 0 },
  { mois: 'Dec 25', mrr: 0 },
  { mois: 'Jan 26', mrr: 0 },
  { mois: 'Fev 26', mrr: 0 },
  { mois: 'Mar 26', mrr: 0 },
  { mois: 'Avr 26', mrr: 0 },
  { mois: 'Mai 26', mrr: 0 },
];

// --- Settings ---
export const mockSettings: Setting[] = [
  { key: 'entreprise_nom', value: 'SOLAYIA', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_forme', value: 'SASU', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_capital', value: '', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_siret', value: '', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_rcs', value: '', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_adresse', value: '', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'entreprise_iban', value: '', updated_at: '2026-01-01T00:00:00Z' },
  { key: 'devis_conditions_default', value: 'Paiement a 30 jours fin de mois', updated_at: '2026-01-01T00:00:00Z' },
];
